# Install pre-commit with: $ pre-commit install
# Install pre-push with: $ pre-commit install --hook-type pre-push
# Run pre-commit: $ pre-commit run --all-files
# For more information, see https://pre-commit.com

default_language_version:
  python: python3.11
# fail_fast: true # stop on first error
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Run black
        args: [--line-length=88]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Run isort
        args:
          [
            --profile=black,
            --trailing-comma,
            --line-width=88,
            --use-parentheses,
            --multi-line=3,
          ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        name: Run autoflake
        args:
          [
            --remove-all-unused-imports,
            --expand-star-imports,
            --ignore-init-module-imports,
            --remove-unused-variables,
            --in-place,
          ]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Run flake8
        args: [--max-line-length=88]
        stages: [push]
  # - repo: local
  #   hooks:
  #     - id: run-tests
  #       name: Run tests
  #       entry: bash -c 'pipenv run python -m pytest -qqq'
  #       language: system
  #       types: [python]
  #       stages: [push]
